# Site settings
baseurl = "http://suarezguisuraga.com/dGhpcyBpcyBqdXN0IGEgYmFzZTY0IHN0cmluZw==/de"
languageCode = "de-DE"
title = "Nadine und Ángel"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
#googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  # name = "Angel Suarez Nadine Heidrich"
  # description = "Boda"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Wir heiraten!"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Die Hochzeit"
    about = "Unsere Geschichte"
    team = "Über uns"
    contact = "Kontakt"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    [[menu.prepend]]
      url = "http://suarezguisuraga.com/dGhpcyBpcyBqdXN0IGEgYmFzZTY0IHN0cmluZw==/es"
      name = "Español"
      weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://1drv.ms/f/s!Al76FgPu2tLSgoILw40VDmYgjHTYzw"
      name = "Fotos"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Nadine und Ángel"
    subtitle = "20. Juli 2018"
    buttonText = "Ich möchte mehr erfahren"


  # Services section
  [params.services]
    enable = true
    title = "Die Hochzeit"
    subtitle = "Hier findet ihr alle wichtigen Infos über die Finca, über León und über den Hochzeitstag."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-home"
      title = "Ablau"
      description = "Die Hochzeitsfeier wird in der Finca <a href='https://goo.gl/maps/vioEXuP8Xq12' target='_blank'>El Molino de los Ajos</a> stattfinden, 15 Autominuten vom Zentrum Leóns entfernt. Am 20. Juli 2018 ist sie exklusiv für uns reserviert sein. <br/>Die Zeremonie beginnt um 19:00 Uhr und die Hochzeitsparty endet in den frühen Morgenstunden. Wir haben einen Busservice für euch reserviert, welcher vom <a href='https://goo.gl/maps/BFpJmoRREKE2' target='_blank'>Hotel Conde Luna</a> um 18:30 Uhr abfährt. Gebt uns bitte vorher Bescheid, ob ihr den Busservice in Anspruch nehmen werdet, damit wir eine Passagierliste für das Busunternehmen vorbereiten können. Seid bitte ca. 15 Minuten vor Abfahrt vor Ort, um sicher zu gehen, dass alle Gäste an Bord sind.<br/> Nach der Ankunft um etwa 19:00 Uhr wird es eine kleine Zeremonie unter freiem Himmel geben gefolgt von einem tollen Aperitif. Gegen 21:30 Uhr wird das Abendessen beginnen und nach dem Dessert und dem traditionellen Tortenanschnitt werden wir euch bei unserem ersten Tanz mit unseren Tanzkünsten beglücken.<br/> Zurück zum Hotel Conde Luna wird es zwei Shuttlebusse geben: Einer fährt gegen 01:30 Uhr morgens ab (nach unserem ersten Tanz) und der zweite am Ende der Feier, ca. gegen 05:00 Uhr."
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-exclamation-circle"
      title = "Wichtige Infos"
      description = "
      <b>Dresscode:</b> Uns ist es wichtig, dass ihr euch wohl fühlt. Auf spanischen Hochzeiten ist es jedoch üblich, sich elegant zu kleiden. In León ist es im Sommer recht warm, nachts kann es aber abkühlen, daher nehmt euch ein Jäckchen mit, um draußen unter dem Sternenhimmel zu tanzen. Mädels, denkt an die Wechselschuhe, damit ihr den ganzen Abend mit uns durchtanzen könnt.<br/><b>Geschenke:</b> Wir freuen uns sehr, dass viele von euch einen weiten Weg auf sich nehmen um zu unserer Hochzeit nach León zu kommen. Deswegen ist euer Kommen bereits das größte Geschenk, das ihr uns machen könnt. Falls ihr dennoch in Schenklaune seid, könnt ihr gern etwas zu unserer nächsten Reise beisteuern.<br/><b>Reis:</b> Achtung! Leider darf in der Finca kein Reis, Konfetti, Feuerwerk oder sonstiges geworfen werden. Daher stellen wir euch Säckchen mit Blütenblättern zur Verfügung, mit denen ihr uns feiern könnt.<br/><b>Programm:</b> Wir möchten keine Spiele an unserem Hochzeitstag machen, sondern einfach nur einen tollen Abend mit euch verbringen. Wenn ihr eine Überraschung für das Abendessen vorbereiten möchtet, setzt euch bitte mit <a href='hannah@dahl.berlin'>Hannah</a> oder <a href='mailto:aalbarranordas@yahoo.es'>Alberto</a> in Verbindung, die diese Programmpunkte koordinieren."
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-map"
      title = "León"
      description = "Wir rechnen damit, dass mehr als 50 Gäste von außerhalb kommen (ihr werdet León erobern!), deshalb findet ihr <a href='https://1drv.ms/w/s!Al76FgPu2tLSgekoBccUtnu79cn1ag' target='_blank'>hier</a> alle wichtigen Infos zu Unterkünften, wichtigen Sehenswürdigkeiten undRouten der Stadt, die wir euch bereits vor einiger Zeit per Email geschickt hatten. Wenn ihr über das Wochenende in León bleibt, gehen wir gern mit euch am Samstagabend aus und entdecken gemeinsam die Stadt. Damit ihr León auch auf eigene Faust unsicher machen könnt, haben wir euch Routen mit unseren Empfehlungen zu den besten <a>Sehenswürdigkeiten</a> und den besten <a>Bars und Restaurants</a> vorbereitet. Wahrscheinlich werdet ihr Fragen zu den Unterkünften oder Unternehmungen in León haben, die wir gern beantworten. Meldet euch einfach per Email an <a href='mailto:suarezguisuraga@gmail.com'>suarezguisuraga@gmail.com</a> oderüber das Kontaktformular auf dieser Seite."
      #url = "#"

    [[params.services.row.list]]
      icon = "fa-spotify"
      title = "Die Musik"
      description = "Nach dem ersten Tanz geht die Fiesta los! Damit wir auch eure Musikwünsche mit einbeziehen können, könnt ihr eure Lieblingslieder in der <a href='https://open.spotify.com/user/sguisu/playlist/2ptH4XgnSYfXeRkrra3iZD?si=zq9AU7S1QsaCkTXkNNsF6w' target='_blank'>Liste hier</a> ergänzen, die wir bei Spotify angelegt haben."

    [[params.services.row.list]]
      icon = "fa-photo"
      title = "Die Fotos"
      description = "Wir haben ein Fotoalbum angelegt, in das wir schon einige Bilder von uns hochgeladen haben. Wir freuen uns, wenn ihr all eure Fotos die ihr an unserem Hochzeitstag macht, mit uns teilt. So schaffen wir einen Ort, an dem alle Gäste Zugang zu alle Bildern haben und keiner der tollen Momente verloren geht. Das Album befindet sich auf <a href='https://1drv.ms/f/s!Al76FgPu2tLSgoILw40VDmYgjHTYzw' target='_blank'>One Drive</a> und es ist genügend Platz für eure Fotos und Videos vorhanden. Der Link ist auch nochmals oben in der Menüleiste unserer Homepage eingefügt, damit ihr schnell Zugriff darauf habt. Es haben nur unsere Gäste mit einem Zugang zu dieser Seite Zugriff auf diese Bilder, welche auch nicht über Suchmaschine zu finden sind. Unangebrachte Bilder werden gelöscht.
      
    # About section
  [params.about]
    enable = true
    title = "Unsere Geschichte"
    #subtitle = ""
    endpoint = "Und nun die Hochzeit"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "August 1982"
      title = "Ángel"
      description = "Ángel wird 1982 geboren, im Jahr der Fußball-Weltmeisterschaft in Spanien, im Jahr von Michael Jacksons ‘Thriller’ und im Jahr, in dem der Film E.T. ein Kassenschlager wird."

    [[params.about.events]]
      img = "2.jpg"
      date = "Februar 1986"
      title = "Nadine"
      description = "Nadine kommt 1986 zu Zeiten des Eisernen Vorhangs in Karl-Marx- Stadt (jetzt Chemnitz) zur Welt. Die Berliner Mauer steht mittlerweile seit 25 Jahren und in der DDR hat sich seit den 70er Jahren wenig verändert. Trabis prägen das Straßenbild und Nadines Leibspeise sind Bananenbrote."

    [[params.about.events]]
      img = "3.jpg"
      date = "2004"
      title = "Nadine und Spanien"
      description = "Nachdem sie sich bereits einige Jahre für die spanische Kultur interessiert, geht Nadine als Au-Pair nach Madrid. Dort verbessert sie ihr Spanisch, entdeckt Tapas und Fiesta und ist so begeistert, dass sie ein weiteres Jahr bleibt."

    [[params.about.events]]
      img = "4.jpg"
      date = "2005"
      title = "Ángel und Madrid"
      description = "Nach dem Studium findet Ángel eine Stelle als Berater in Madrid. Er arbeitet viel und hat kaum Zeit zum Ausgehen und Amüsieren. Außerdem fährt er fast jedes Wochenende in sein geliebtes León zurück, wo alles so ist wie früher…"

    [[params.about.events]]
      img = "5.jpg"
      date = "Marzo 2006"
      title = "Casa de la cerveza"
      description = "Nadine trifft man zu dieser Zeit in typischen Madrider Institutionen (mit viel Bier) und Ángel zieht viel mit seinen Mitbewohnern und Arbeitskollegen um die Häuser. Im März 2006 passiert es dann in einer siffigen Madrider Bar: eine Gruppe deutscher Mädels trifft auf eine Gruppe spanischer Jungs und endlich lernen sich Nadine und Ángel kennen."

    [[params.about.events]]
      img = "6.jpg"
      date = "2006 und 2007"
      title = "Erster Teil"
      description = "Ein paar Sommermonate in Madrid, ein paar Wochenenden in León, Flüge nach Mannheim, wo Nadine mit ihrem Studium beginnt, die Semesterferien in Madrid, ein Wochenende in Barcelona und noch mehr Wochenenden. Eine unvergleichbare Geschichte über zwei Jahre voller magischer Momente. Aber manchmal kann auch das Gute über die Distanz nicht für immer halten…"

    [[params.about.events]]
      img = "7.jpg"
      date = "2014 - 2017"
      title = "Zweiter Teil"
      description = "Viele Jahre auf getrennten Wegen, viele neue Städte und viele wunderbare Freundschaften fürs Leben - Barcelona, Málaga, Regensburg, München, Madrid, Zürich, Berlin. Aber Nadine bleibt immer Nadine und Ángel bleibt immer Ángel. Und schließlich veränderte Ende 2014 ein Anruf alles und die Geschichte begann wieder von vorn."

    [[params.about.events]]
      img = "8.jpg"
      date = "Sicilia 2017"
      title = "Der Antrag"
      description = "Und nach 3 Jahren des zweiten Teils ist klar, dass diese Geschichte ernst wird. Fast keiner wusste, dass Ángel etwas ganz Spezielles für die Sizilienreise geplant hatte. In Taormina, im Sonnenuntergang, mit Blick auf das Mittelmeer und den Vulkan Ätna kniet er sich vor sie und stellt DIE Frage, welche Nadine mit „Ja“ beantwortet."

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = true
    title = "Über uns"
    subtitle = "Wir möchten keine Romane verfassen, aber neben unserer Geschichte möchten wir auch uns vorstellen, damit ihr wisst (falls ihr es bisher noch nicht wusstet) wer wir sind, was wir mögen und was nicht. Außerdem haben wir ein paar Link zu unseren Sozialen Netzwerken eingefügt."
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "1.jpg"
      name = "Nadine"
      position = "Die Braut, Naddl"
      # For bio markdown and even multiline strings are available.
      bio = """Sie mag gesundes und gutes Essen und jegliche Art Kräutertee. Sie isst wenig Fleisch, aber liebt frischen, gegrillten Fisch. Außerdem trinkt sie gern Gin Tonics und guten Wein (am liebsten aus Spanien und Italien).  Sie liebt die Natur und die Sonne. Deswegen trainiert sie in ihrer Freizeit in einem Drachenboot- Team. Sie macht gern kleine Geschenke und mag keine teuren Dinge. Sie tanzt gern zu Reggeaton und Latinomusik. Sie mag die Farbe Orange nicht, aber liebt frisch gepressten Orangensaft. Sie ist Perfektionistin und wird rot wie eine Tomate, wenn sie mit fremden Menschen spricht."""
      social = [
        ["fa-facebook", "https://www.facebook.com/nadine.heidrich.75"],
        ["fa-phone", "tel:+4917696900725"]
      ]

    [[params.team.members]]
      img = "2.jpg"
      name = "Ángel"
      position = "Der Bräutigam, Guisu, Pichu"
      bio = """Er mag die Farbe Grün. Er liebt Craft Beer und Bourbon. Er isst alles gern, was auf den Tisch kommt, vor allem Fleisch. Außer Leber, die mag er nicht. Es fällt ihm schwer sich auf ein Thema zu konzentrieren. An León vermisst er am meisten die Sonne bei Minusgraden und die Berge. Er mag keine Fanatiker egal welche Richtung und keine Pseudowissenschaften. Er hört gern guten Rock und Punk aus den 90er Jahren. Seine ironische Art hat ihn mehr als einmal in Missverständnisse verwickelt."""
      social = [
        ["fa-twitter", "https://twitter.com/sguisu"],
        ["fa-instagram", "https://www.instagram.com/elguisu"],
        ["fa-whatsapp", "tel:+34609282042"],
        ["fa-phone", "tel:+4915168812734"]
      ]

      [[params.team.members]]
      img = "3.jpg"
      name = "Ángel und Nadine"
      position = "Das Brautpaar"
      bio = """Sie kennen sich seit 12 Jahren und ihre Lieblingsstadt ist Madrid. Seit über 3 Jahren leben sie zusammen in Ostberlin in einer schönen Wohnung mit Gästezimmer (wichtige Info für alle, die die Hauptstadt mit uns entdecken möchten!). Sie kochen gern zusammen, haben eine Hausbar und klar eingeteilte Aufgaben im Haushalt. Auch wenn sie die spanische Sonne vermissen, genießen sie Berlin mit seinen zahlreichen tollen Restaurants und entdecken jeden Tag neue Ecken der Stadt. Sie lieben es zu reisen. Die letzten unvergesslichen Orte, an denen sie gemeinsam waren, sind Kolumbien, Vietnam, Amsterdam, London, Sizilien und Kuba."""
      social = [
        ["fa-send", "mailto:suarezguisuraga@gmail.com"]
      ]

  # Contact section
  [params.contact]
    enable = true
    title = "Contacto"
    subtitle  = "Wenn ihr Fragen oder Anregungen habt, schreibt uns eine Email an <a href='mailto:suarezguisuraga@gmail.com'>suarezguisuraga@gmail.com</a> oder über das Kontaktformular."
    buttonText = "Enviar"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "suarezguisuraga@gmail.com"

    # Success and error message overwrite for async contact form
    thanks = "Danke für deine Nachricht!"
    error = "Opala! Diese Nachricht wurde nicht gesendet. Versuch es noch einmal mit suarezguisuraga@gmail.com."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Name *"
      warning = "Es fehlt dein Name"

    [params.contact.form.email]
      text = "Email *"
      warning = "Es fehlt deine Email Adresse"

    [params.contact.form.phone]
      text = "Telefonnummer *"
      warning = "Es fehlt deine deine Nummer "

    [params.contact.form.message]
      text = "Nachricht *"
      warning = "Es fehlt eine Nachricht"

